[package]
name = "netbencher_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["full"]}
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"
log = { version = "*"}
simplelog = "^0.12.0"
clap = "4.1.1"